apps/analysis/urls.py
from django.urls import path
from .views import analyze_view, report_view , heatmap_data , city_suggestions
app_name = "analysis"
urlpatterns = [
    path("", analyze_view, name="analyze"),
    path("report/<int:pk>/", report_view, name="report"),
    path("heatmap-data/", heatmap_data, name="heatmap-data"),
    path("ajax/city_suggestions/", city_suggestions, name="city_suggestions"),
]

apps/core/urls.py
from django.urls import path
from .views import home 
app_name = "core"
urlpatterns = [
    path("", home, name="home"),
    

]

apps/dashboard/urls.py
from django.urls import path
from .views import dashboard_view ,map_view
app_name = "dashboard"
urlpatterns = [
    path("", dashboard_view, name="dashboard"),
    path("map/", map_view, name="map"),
]

apps/users/urls.py
from django.urls import path
from .views import register_view, profile_view
from django.contrib.auth import views as auth_views
app_name = "users"
urlpatterns = [
    path("register/", register_view, name="register"),
    path("login/", auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("profile/", profile_view, name="profile"),
]

citysense/urls.py
from django.contrib import admin
from django.urls import path , include
from apps.core import views
urlpatterns = [
    path("", include("apps.core.urls")),
    path('admin/', admin.site.urls),
    path("users/", include("apps.users.urls")),
    path("analysis/", include("apps.analysis.urls")),
    path("reports/", include("apps.reports.urls")),
    path("dashboard/", include("apps.dashboard.urls")),
    path("community/", include("apps.community.urls")),


]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{% block title %}CitySense{% endblock %}</title>
<link rel="icon" type="image/svg+xml" href="{% static 'images/favicon.svg' %}">
<link rel="stylesheet" href="{% static 'css/base/all.min.css' %}">
<link rel="stylesheet" href="{% static 'css/base/base.css' %}">


{% block extra_css %}{% endblock %}
</head>
<body>


    {% include 'base/header.html' %}


<main>
    {% block content %}{% endblock %}
</main>
<div id="auth-modal" class="auth-modal hidden">
 <div class="auth-box">
     <h3>Login Required</h3>
     <p>You need an account to access this feature.</p>

     <div class="actions">
         <a href=" {% url 'users:login' %} " class="btn primary">Login</a>
         <a href="{% url 'users:register' %}" class="btn secondary">Create Account</a>
     </div>

     <button class="close-btn">&times;</button>
 </div>
</div>

  {% include 'base/footer.html' %}


{% block extra_js %}{% endblock %}

<script src="{% static 'js/base/base.js' %}"></script>

</body>
</html>

templates/base/footer.html
<footer>
    <div class="container footer-container">
        <div class="footer-grid">
            <div>
                <h3>CitySense</h3>
                <p>AI-powered insights on urban living for better decision-making.</p>
                <div class="social-icons">
                    <a href="#" aria-label="Facebook"><i class="fab fa-facebook-f"></i></a>
                    <a href="#" aria-label="Twitter"><i class="fab fa-twitter"></i></a>
                    <a href="#" aria-label="LinkedIn"><i class="fab fa-linkedin-in"></i></a>
                    <a href="#" aria-label="Instagram"><i class="fab fa-instagram"></i></a>

                </div>
            </div>
            <div>
                <h3>Quick Links</h3>
                <ul>
                    <li><a href="{% url 'core:home' %}">Home</a></li>
                    <li><a href="{% url 'dashboard:dashboard' %}" class="auth-required">Dashboard</a></li>
                    <li><a href="{% url 'analysis:analyze' %}" class="auth-required">Analysis</a></li>
                </ul>
            </div>
            <div>
                <h3>Contact</h3>
                <p>Email: nasserattia60@gmail.com</p>
                <p>Phone: +20 0111 0404 431</p>
            </div>
        </div>
        <p class="bottom-text">© 2026 CitySense. All rights reserved.</p>
    </div>
</footer>

templates/base/header.html
<header>
    <div class="container header-container">
        <a href="{% url 'core:home' %}" class="logo">CitySense</a>
        <nav>
            <ul class="nav-links">
                <li><a href="{% url 'core:home' %}" >Home</a></li>
                <li><a href="{% url 'dashboard:dashboard' %}" class="auth-required">Dashboard</a></li>
                <li><a href="{% url 'analysis:analyze' %}" class="auth-required">Analysis</a></li>
                <div class="user-menu">
                    {% if user.is_authenticated %}
                        <a href="{% url 'users:profile' %}">Profile</a>
                        <form method="post" action="{% url 'users:logout' %}">
                            {% csrf_token %}
                        <button type="submit">Logout</button>
                        </form>
    
                    {% else %}
                        <a href="{% url 'users:login' %}">Login</a>
                        <a href="{% url 'users:register' %}">Sign Up</a>
                    {% endif %}
                </div>
            </ul>
        </nav>
        <div class="mobile-menu-toggle">☰</div>
    </div>
</header>