apps/reports/urls.py
from django.urls import path
from .views import reports_list_view
app_name = "reports"
urlpatterns = [
    path("", reports_list_view, name="reports"),
]

apps/users/urls.py
from django.urls import path
from .views import register_view, profile_view
from django.contrib.auth import views as auth_views
app_name = "users"
urlpatterns = [
    path("register/", register_view, name="register"),
    path("login/", auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("profile/", profile_view, name="profile"),
]

citysense/urls.py
from django.contrib import admin
from django.urls import path , include
from apps.core import views
urlpatterns = [
    path("", include("apps.core.urls")),
    path('admin/', admin.site.urls),
    path("users/", include("apps.users.urls")),
    path("analysis/", include("apps.analysis.urls")),
    path("reports/", include("apps.reports.urls")),
    path("dashboard/", include("apps.dashboard.urls")),
    path("community/", include("apps.community.urls")),


]

apps/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    email = models.EmailField(unique=True)
    
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["username"]

    def __str__(self):
        return self.email


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    city = models.CharField(max_length=100, blank=True)
    avatar = models.ImageField(upload_to="avatars/", blank=True)

    def __str__(self):
        return f"{self.user.email} Profile"

apps/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User, Profile

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["email", "username", "password1", "password2"]

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["bio", "city", "avatar"]

apps/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from .forms import RegisterForm, ProfileForm
from django.contrib.auth.decorators import login_required
from .models import Profile


# Create your views here.



from django.contrib.auth.models import User

def register_view(request):
    form = RegisterForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("core:home")
        else:
            if "username" in form.errors or "email" in form.errors:
                return redirect("users:login")
    return render(request, "users/register.html", {"form": form})





@login_required
def profile_view(request):
    profile, created = Profile.objects.get_or_create(user=request.user)
    

    form = ProfileForm(
        request.POST or None,
        request.FILES or None,
        instance=profile
    )
    if form.is_valid():
        form.save()

    context = {
        "form": form,
        "user": request.user,
        "profile": profile,
    }
    return render(request, "users/profile.html", {"form": form, "context": context})

templates/users/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="CitySense - AI-powered insights on safety, noise, rent, and water quality for any address.">
    <title>Login | CitySense</title>

    <link rel="stylesheet" href="{% static 'css/users/style.css' %}">
</head>

<body class="auth-page">

    <main class="auth-wrapper">

        <section class="auth-card glass">

            <header class="auth-header">
                <h1>Welcome Back</h1>
                <p>Sign in to access your CitySense dashboard</p>
            </header>

            <form method="POST" action="{% url 'users:login' %}" class="auth-form">
                {% csrf_token %}
                {{ form.as_p }}

                <button type="submit" class="btn primary-btn">
                    Login
                </button>
            </form>

            <footer class="auth-footer">
                <p>
                    Don't have an account?
                    <a href="{% url 'users:register' %}">Create one</a>
                </p>
            </footer>

        </section>

    </main>

</body>
</html>
 
   

templates/users/profile.html
{% extends "base/base.html" %}
{% load static %}
{% block title %}CitySense | profile {% endblock %}
{% block extra_css %}
<link rel="stylesheet" href=" {% static 'css/users/profile.css' %}">
{% endblock %}
{% block content %}

<div class="dashboard">

    <!-- Sidebar -->
    <aside class="sidebar">
        <h2 class="logo">CitySense</h2>
        <ul class="menu">
            <li class="active">Profile</li>
            <li><a href="{% url 'reports:reports' %}" style='text-decoration: none;color: #fff;'>Reports</a></li>
            <li>setting</li>
            <li>
              <form method="post" action="{% url 'users:logout' %}">
                {% csrf_token %}
                <button type="submit" style='background-color: #111827;border: none;color: #fff;' class='bt_fo'>Logout</button>
              </form>
            </li>
        </ul>
    </aside>

    <!-- Main Content -->
    <main class="content">

        <!-- Profile Header -->
        <section class="profile-header">
            <div class="avatar">
                <img src="{% static '{{ profile.avatar.url }}' %}" >
            </div>
            <div class="info">
                <h1>{{ context.user.username }}</h1>
                {% if context.profile.bio %}
                 <p><strong>Bio:</strong> {{ context.profile.bio }}</p>
                {% endif %}
                <span class="badge">Premium User</span>
            </div>
        </section>

        <!-- Profile Details -->
        <section class="profile-details">
            <div class="card">
                <h3>Email</h3>
                <p>{{ context.user.email }}</p>
            </div>

            <div class="card">
                <h3>Location</h3>
                <p>{{ context.profile.city }}</p>
            </div>

            <div class="card">
                <h3>Member Since</h3>
                <p>Jan 2024</p>
            </div>
        </section>

        <!-- About -->
        <section class="about">
            <h2>About Me</h2>
            <p>
                Passionate software engineer with a focus on AI, web development,
                and building scalable systems that actually work in real life.
            </p>
        </section>

    </main>

</div>

{% endblock %}
{% block extra_js %}
{% endblock %}

templates/users/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="CitySense - Create your account and access AI-powered urban insights.">
    <title>Register | CitySense</title>

    <link rel="stylesheet" href="{% static 'css/users/style.css' %}">
</head>

<body class="auth-page">

    <main class="auth-wrapper">

        <section class="auth-card glass">

            <header class="auth-header">
                <h1>Create Account</h1>
                <p>Join CitySense and explore smarter urban insights</p>
            </header>

            <form method="post" class="auth-form">
                {% csrf_token %}
                {{ form.as_p }}

                <button type="submit" class="btn primary-btn">
                    Create Account
                </button>
            </form>

            <footer class="auth-footer">
                <p>
                    Already have an account?
                    <a href="{% url 'users:login' %}">Login</a>
                </p>
            </footer>

        </section>

    </main>

</body>
</html>
  